---
version: '3'
services:
    maven:
        build:
            context: ./docker
            dockerfile: tomcat.dockerfile
        volumes: war:/home/user/boxfuse-sample-java-war-hello/target/
   
    tomcat: 
        image: tomcat:9.0-alpine    
        ports:
             - '8080'
        volumes: war:/usr/local/tomcat
volumes: 
        war: 
        
             