---
version: '3'
services:
    maven:
        build:
            context: ./docker
            dockerfile: tomcat.dockerfile
        volumes:
   
    tomcat: 
        image: tomcat:9.0-alpine    
        ports:
             - '8080'
        volumes:
             