---
version: '3'
services:
    maven:
        build:
            context: ./docker
            dockerfile: mvn.dockerfile
        volumes: 
             - war-storage:/home/user/boxfuse-sample-java-war-hello/target/
   
    tomcat: 
        image: tomcat:9.0-alpine    
        ports:
             - '8080:8080'
        volumes: 
             - war-storage:/usr/local/tomcat/webapps
volumes: 
    war-storage: 
        
             